specVersion: "0.2.0"

name: "Frontier EVM Starter Project"
version: "1.0.0"
description: "A basic Frontier EVM example project with an event and call handler. Read more about this at https://doc.subquery.network/create/frontier/"
repository: "https://github.com/cheesekon/mb-test"

schema:
  file: "./schema.graphql"

network:
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  endpoint: wss://wss.api.moonbase.moonbeam.network
  dictionary: https://api.subquery.network/sq/subquery/moonbeam-dictionary
  chaintypes:
    file: ./dist/chaintypes.js

dataSources:
  - kind: substrate/FrontierEvm
    startBlock: 1953000
    processor:
      file: './node_modules/@subql/contract-processors/dist/frontierEvm.js'
      options:
        abi: contract
        address: '0x7546601D838bebd9108894a557d533311090Dad8'
    assets:
      contract:
        file: './contract.abi.json'
    mapping:
      file: './dist/index.js'
      handlers:        
        - handler: handleListedEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics: 
              - Listed(address from, address to,uint256 sopo_id, uint256 nft_id, address nft_programe_address)

        - handler: handleList
          kind: substrate/FrontierEvmCall
          filter:
            function: list(uint256,address)